apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfm
  namespace: monitoring
data:
  prometheus.yml: |
    global:
    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'kube-api-blackbox'   # test
        scrape_interval: 15s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
        - targets:
            - https://www.google.com
            - https://prometheus.io
            - https://tinhte.vn
